apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myweb-rs
spec:
    replicas: 3
    selector:
         matchLabels:
             - env: production
             - country: us
    template:
        metadata:
            name: myweb-pod
            labels:
                country: us
                dc: "2"
                env: production
        spec:
            containers:
                - name: myweb-con
                  image: httpd
